-- Esquema inicial: identidad (users, roles, user_roles) y auditoría (audit_log).
-- Los recursos clínicos (Patient, Practitioner) viven en el HAPI FHIR central,
-- no en este MS, así que no se crean tablas para ellos.
--
-- Sintaxis SQL:2008 (GENERATED BY DEFAULT AS IDENTITY) compatible con
-- PostgreSQL 10+ y H2 2.x en modo PostgreSQL.

CREATE TABLE roles (
    role_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50)  NOT NULL UNIQUE,
    description  VARCHAR(200)
);

CREATE TABLE users (
    user_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username               VARCHAR(60)  NOT NULL UNIQUE,
    password               VARCHAR(100) NOT NULL,
    email                  VARCHAR(150) NOT NULL UNIQUE,
    active                 BOOLEAN      NOT NULL,
    mfa_secret             VARCHAR(64),
    mfa_enabled            BOOLEAN      NOT NULL DEFAULT FALSE,
    failed_login_attempts  INTEGER      NOT NULL DEFAULT 0,
    locked_until           TIMESTAMP,
    last_login_at          TIMESTAMP,
    practitioner_fhir_id   VARCHAR(64)
);

CREATE TABLE user_roles (
    user_id  BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    role_id  BIGINT NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    VARCHAR(32)  NOT NULL,
    username      VARCHAR(60),
    user_id       BIGINT,
    resource_type VARCHAR(32),
    resource_id   VARCHAR(64),
    ip_address    VARCHAR(45),
    user_agent    VARCHAR(200),
    endpoint      VARCHAR(200),
    jti           VARCHAR(36),
    break_glass   BOOLEAN      NOT NULL DEFAULT FALSE,
    reason        VARCHAR(500),
    occurred_at   TIMESTAMP    NOT NULL
);

CREATE INDEX idx_audit_username ON audit_log(username);
CREATE INDEX idx_audit_resource ON audit_log(resource_type, resource_id);
CREATE INDEX idx_audit_occurred ON audit_log(occurred_at);
